### ISSUE TITLE
Can  'StackExchange.Elastic'   be compatible with Elastic Search 2.0?

### ISSUE THREAD

**Issue by yuzukwok** [opserver/Opserver#109]
HI, I'm using OpServer with  Elastic Search 2.0 . It doesnot work well.When I debug the code of OpServer,I found that some deserialize exception  throw by 'StackExchange.Elastic'.  Is StackExchange.Elastic  a open source project? I want to fix  this problem that bothers me.

**Comment by NickCraver** [comment]
So a bit of a yes and no answer here. Yes this is fixed [in the overhaul branch](https://github.com/opserver/Opserver/commits/overhaul), but I still need to wrap a few things up there before it goes into master (mainly /hub and SQL table rows). Under extremely heavy load on startup there can be a delay on thread starvation I'm working out, this just translates into a slow start after a build if many are hitting it. This branch has many other changes and I'm still tweaking the UI (which is now mobile friendly, etc.) but it is ElasticSearch 2.x ready. If you want to try it and give any feedback - I'd be very appreciative.

As for StackExchange.Elastic, I doubt it will ever be open source simply because it'd be a disservice to the community to release it. It's quite literally a subset of the APIs in Elasticsearch that we use - which is comparatively very few. In overhaul you'll see that I just removed the dependency and brought the monitoring classes and bits in-house because so little applies outside of Opserver's usage anyway. I strongly believe releasing such an "incomplete" client library will only cause more confusion and fragmentation than good. I'm not particularly against the source being out there per se, but I'd argue it should never go to NuGet unless it covered significantly more API surface area.

**Comment by yuzukwok** [comment]
Thank you very much. I will try the overhaul branch.

**Comment by NickCraver** [comment]
@yuzukwok heads up: it looks like the shards view isn't working correctly...I'll figure that out and fix tonight.

**Comment by NickCraver** [comment]
@yuzukwok fixed - let me know if you hit any 2.x issues please!

**Comment by NickCraver** [comment]
Closing this out since support is in the overhaul branch!
