### ISSUE TITLE
Publishing and Form issue

### ISSUE THREAD

**Issue by CouchFrancois** [opserver/Opserver#118]
I've tried to figure this out for hours, throwing it out here as a last resort.

I got everything set up quick and easy **locally, it works just fine** connecting to our sql instances.  Publishing is another matter.  Using a **file publish** to our IIS box, same way I do for other projects.  But when I do that, the only thing I can get the published version to do is go to the login page.  No matter what you do or don't enter it sticks to the form authentication.  And the css styles do not show up as well.

I have security set up to alladmin.  I did see the previous closed issue with styles not showing up in the form having to do with permissions.  I have the anonymous authenticated user with full permissions to everything in the opserver directory.  IIS authentication is set at anonymous and form authentication (values from web.config)

Any ideas?

**Comment by NickCraver** [comment]
Well I guess that makes sense, because the .config files aren't in the project. I'm not sure how we can fix this without creating *more* problems, but possibly empty configs...let me think about it tonight.

As a quick fix, include your Config\*.config files in the project - I'll think about how to fix such a case for everyone given those files are (and need to be) .gitgnored.

**Comment by CouchFrancois** [comment]
Yeah, I had noticed that the configs weren't being published, so I copied
those up as well. So the issue as I described it was with a security and
sql config copied up

**Comment by NickCraver** [comment]
@CouchFrancois can you post what you security config looks like (removing passwords if present)? Off the top of my head: perhaps the account you're running the application pool as (maybe `IIS AppPool\<name>`?) doesn't have permission to bind to LDAP/AD. I often see this if anonymous binds aren't enabled, which is the default.

**Comment by CouchFrancois** [comment]
Nothing special about the security config, I'm running this as a POC on an internal development box so there isn't a need for enhanced security at the moment
`<?xml version="1.0" encoding="utf-8"?>
<SecuritySettings provider="alladmin" />`

I was setting up my AD account as the anonymous account and the application pool account thinking that that would emulate running it locally, but my AD account ended up being locked :stuck_out_tongue_closed_eyes: and being a Sunday probably won't be unlocked until tomorrow.

Any more ideas please let me know.

**Comment by Tony-Mc** [comment]
When I tried running on Local IIS instead of IIS Express I experienced something similar to what @CouchFrancois is describing.

I hosted application as Opserver.
When I opened `localhost/Opserver` it redirected me to `localhost/login?ReturnUrl=%2FOpserver`. That's the root of IIS instead of app's root.

![image](https://cloud.githubusercontent.com/assets/8818187/13206088/0d49640c-d900-11e5-9b92-0e65bd8ae136.png)

Opening `localhost/Opserver/login` resulted in a login form without styles which when logging in leads to another 404.

 ![image](https://cloud.githubusercontent.com/assets/8818187/13206074/b21647da-d8ff-11e5-8fea-cce4cd20d7b4.png)

So I dug around and found some redirects to urls like `"/login?ReturnUrl="` and that made sense - I'm redirecting to IIS root, I added a tilde `~/login?ReturnUrl=` so it would redirect to App root, after this change `localhost/Opserver` -> `localhost/Opserver/login?ReturnUrl=%2FOpserver`. 

To fix styles I removed the first slashes in CSS links in `Login.cshtml` so it would look like `"Content/themes/light/styles.min.css"`.

![image](https://cloud.githubusercontent.com/assets/8818187/13206244/c2696ce0-d902-11e5-95ed-f3d43b3939db.png)

Next problem was login form action posting to `/login` which logged me in after being changed to `~/login`.

I also changed `Redirect(url)` calls in `LoginController.cs` and `SQLController.cs` to have `~` at the beginning. This way login works as expected on my Local IIS but now I'm at this view, which made me think I might be digging too deep. So my question is am I on the right track and should I keep going?

![image](https://cloud.githubusercontent.com/assets/8818187/13206389/a4cd668e-d905-11e5-95e7-1b4dc9f05bad.png)

After all this I've switched back to IIS Express to see if I broke anything, It looked alright so I think app root urls worked as expected.

I've put all the changes except configuration files here: https://github.com/Tony-Mc/Opserver/tree/UrlRoutingFix 

My configuration.

**Web.config**
```
<add key="ViewGroups" value="*" />
<add key="AdminGroups" value="*" />
```

I'm running on:
IIS 8.5

AppPool:
CLR version: v4.0
Managed Pipeline: Integrated
Identity: ApplicationPoolIdentity

Security and other configs are there (I even included the files to .sln, just in case).

**Comment by NickCraver** [comment]
The problems @Tony-Mc point out make sense here - Opserver explicitly doesn't support running under a virtual path but only for performance reasons. I *want* to change most links to use things like `ActionLink()`, etc. but it's terribly slow with many routes in MVC 5 due to how it's implemented. However, it's totally re-written and usable for MVC 6.

MVC 6 is on my radar, since that's a big step in getting Opserver running on Linux as well. However, there's a decent amount of work before that can happen. I'll have to do a lot of work on Exceptional and MiniProfiler to get those libs running on .Net Core. 

I'm not against doing `~/` paths (the blocker for doing so has been removed), I'll take a big stab at it this morning. That should probably fix ~90% of the problem, the others I'll try to click around a full working model (I have everything but Jira setup locally) and ensure virtual directories work.

**Comment by Tony-Mc** [comment]
Should I continue working on my branch or will you take over from here? Because I can't wait to run Opserver ;)

**Comment by NickCraver** [comment]
@Tony-Mc I'll grab it - working locally now. After kids are out I'll figure out how to best resolve the tabs and such - already have the backend working. Hang on, I'll update here when the first wave of fixes is in (just a few hours, solving some Stack Overflow issues too).

**Comment by Tony-Mc** [comment]
Sure, great!

**Comment by NickCraver** [comment]
@Tony-Mc I just pushed the server-side which you can see in https://github.com/opserver/Opserver/commit/d2fe71e01a2bad1a40591f1afc6050ddeb25b8a0, AJAX requests still need love which I'll do next. Give it a try and you should be able to browse around pretty well at this point. I'm looking at how to most cleanly solve the pathing issue in JS now.

**Comment by NickCraver** [comment]
Okay I addressed what I think are all the AJAX issues as well - can you please give latest a test @Tony-Mc? Commit is here if curious: https://github.com/opserver/Opserver/commit/0208ee407cdeb852cdda758e37e417151384a34b

**Comment by Tony-Mc** [comment]
@NickCraver everything works great. Well done!

**Comment by NickCraver** [comment]
Excellent! @CouchFrancois can you please give latest `overhaul` code a try and see if this was your issue as well?

**Comment by CouchFrancois** [comment]
I didn't have high hopes b/c I'm not using a virtual directory.  Still
seeing the same issue, although I do love the new interface

Here's what I get:

[image: Inline image 1]

**Comment by NickCraver** [comment]
@CouchFrancois your image didn't come through in GitHub (doesn't work when replying via email), can you add again please?

**Comment by CouchFrancois** [comment]
It's nothing spectacular...

![image](https://cloud.githubusercontent.com/assets/1000466/13289603/2301c8fc-dad6-11e5-8b82-eea1e7e727f0.png)

**Comment by CouchFrancois** [comment]
NM, I got it to work.  .Net authorization in IIS wasn't set up correctly.  Thanks everyone for your help

**Comment by Tony-Mc** [comment]
@NickCraver I think this can be closed.
