### ISSUE TITLE
Hammering a SQL Instance doesn't mark it as critical

### ISSUE THREAD

**Issue by VictoriaD** [opserver/Opserver#136]
I purposely ran a big query on my sql instance, and reduced the page life expectancy to 2 seconds. However, on the `sql/servers` page it was happily marked as green and pootling along. Is there a way to specify Crtiical and Warning levels for the various items on an instance? Can this be done through the SQLSettings.json page?

**Comment by NickCraver** [comment]
There are no thresholds for that metric (or many others) in terms of alerting, because there's no "right" on them I can build in. I can look at such settings, but it'll be a while before new (rather expansive) functionality like that lands. In our systems, we're typically alerting from Bosun (which sends email, etc.). The "alerting" functionality of Opserver is very purposefully minimal at this point, focusing on other feature areas.

**Comment by VictoriaD** [comment]
OK, thanks! I was hoping to use Bosun, but unfortunately can't seem to get it working!
