### ISSUE TITLE
Using vs 2010 and it is telling me it can't open the csproj

### ISSUE THREAD

**Issue by bzelli** [opserver/Opserver#15]

**Comment by NickCraver** [comment]
I'm going to close this out simply because it'll need VS 2015 going forward *to work on*, but with (hopefully as soon as we can) a .Net Core port it'll also become accessible from the command line. There are many dependency blockers for a CoreCLR port, but many others and myself are working on all of them at once. AD authentication will be the biggest hurdle that's very likely post-RTM.
