### ISSUE TITLE
Logging removed plans

### ISSUE THREAD

**Issue by PeteGoo** [opserver/Opserver#150]
We have a need to be able to log the removed plans for better insight and post-analysis. Are there plans to add log4net or similar? Is there another way to achieve this?

**Comment by NickCraver** [comment]
There are no plans to do this, because plans go in and out of cache all the time just as a matter of normal operation in SQL Server. I'm not sure there's any need though. I'd recommend simply downloading the plan (via a link on the same panel) before clicking remove if you want to save it for analysis.

SQL also has new support for this in an alternative way coming in 2016 with the Query Data Store. I plan to add Opserver support for this as well; you can see the history of plans, revert to old plans, etc. Here's a getting-started read on what QDS functionality allows: https://www.brentozar.com/archive/2014/11/sql-server-query-store/

**Comment by PeteGoo** [comment]
Thanks, the query data store sounds perfect. The idea for us is to push the plan details to an aggregated log store like sumologic so we can easily analyse it later for correlation with performance metrics. Downloading the plans makes this harder to do and adds friction for sleepy ops people.

I figured it might be a bit specific to us. Will probably just fork for what we need until a better option arises.

Thanks

**Comment by PeteGoo** [comment]
@NickCraver Don't suppose you ever added Query Store support somewhere I can't see?

**Comment by NickCraver** [comment]
@PeteGoo I haven't yet, no. But I've picked up recently, we're working out the .NET Core and Docker kinks, then since we're now using Query Store at Stack Overflow, I intend to poke it as a new feature in the coming weeks. #355 is almost ready :)

**Comment by PeteGoo** [comment]
Excellent. Thanks
