### ISSUE TITLE
WMI graphs only contain ~3 hour of data

### ISSUE THREAD

**Issue by itssimple** [opserver/Opserver#208]
Is there a way to increase the amount of data that the WMI-provided servers can serve?

Currently it only shows the latest 3 hours, while the scollector ones contain much more.
And last time I had a server on WMI and scollector, there was a duplicate server, that didn't work.

**Comment by NickCraver** [comment]
Which branch are you using (overhaul or master)? WMI history is in-memory and defaults to 24 hours (but is adjustable). So if the application is restarting, that would mean a restart to history's starting point. The setting is `historyHours` (integer) in the WMI settings section. Here's an example minimal config:

``` json
{
  "providers": {
    "wmi": {
      "nodes": [ "ny-web01" ],
      "historyHours": 24
    }
  }
}
```

The node overlap is another issue which I'm not really sure how to go about. Using multiple providers for every attribute is a bit nuts on so many layers, but preferring a provider before another may be reasonable as to which node should "count". It's so rare though, that also may not be worth it - since it introduces poll races, addition/removal races, etc. into the mix.

**Comment by itssimple** [comment]
We're using `overhaul`.
I've set the AppPool to never recycle, so I'll check if I can set historyHours when I'm back at work.

**Comment by NickCraver** [comment]
I occurred to me, you likely also have an old version - I upped the default to 24 hours a while back: https://github.com/opserver/Opserver/commit/0abe8c9566952f4c5be17868b617b560d1af0ebd

**Comment by itssimple** [comment]
Our config said 2 hours, so I upped it to 24 hours now, thanks!
We're using the version that's available from nuget
