### ISSUE TITLE
How to load balance Opserver?

### ISSUE THREAD

**Issue by itssimple** [opserver/Opserver#270]
Currently we have a HAProxy with 3 web servers up and running.

Is there some way to make Opserver load balanced, so it doesn't have to poll WMI-data among other services on all web servers?

Not that 3 connections to each service is too much, but I just wondered if it was possible. :)

And yes, Opserver is running on all 3 web servers, pool recycling is off.

**Comment by NickCraver** [comment]
At the moment, the best way to do that would be to place 2 of the 3 servers in backup mode so that only one spins up by default (this is what we do). At the moment, sharding of load isn't supported though it's a place I'd like to get to for security reasons as well. The end goal is to have the polling service run in one place and the web front-end access it from many (possible in a less secure area). There's a lot to do to make this happen though, so I have no timeline on it.

**Comment by NickCraver** [comment]
Closing out to cleanup, answered above!
