### ISSUE TITLE
TeamCity support?

### ISSUE THREAD

**Issue by bmmathe** [opserver/Opserver#84]
There is a TeamCity settings json file yet I couldn't find a controller for builds or TeamCity.
It looks like there is code to support connecting to the TeamCity rest API and gathering information about builds but no view for it.  Is this coming in a later release?

**Comment by NickCraver** [comment]
They are present, but in a very simplistic way: adding build dots and info to server charts. Now that TC 9 is out and we're fully on nested builds I can support a pattern for builds rather than a list of the old/unintuitive "btNN" format. For example we can do `ProjectName_Folder_*` maps to `X` server group and all builds in that folder show up there. Possibly with a regex for include/exclude since ignoring dev builds makes sense to most, etc.

I'll try and give this some love next week - we've admittedly not used it much at Stack Exchange due to the nature of how builds names were defined in TC < 8.0. Aliases make this way better, and I'll add some features to make use of them.

**Comment by NickCraver** [comment]
Update: for now, I have removed this completely (as it was unused and stands in the way of .Net Core support). Since it's rather unlikely that the lib I used will be supported on .Net Core (and had many dependencies), I'll have to re-implement the REST bits on the other side.

**Comment by NickCraver** [comment]
Going to close this out as I don't see adding support anywhere in the near future for TeamCity - it's just not an area that'll see any investment.
