### ISSUE TITLE
Bosun integration in Opserver

### ISSUE THREAD

**Issue by enmik** [opserver/Opserver#87]
We are currently using Opserver and are planning to test Bosun. However, the Bosun branch seems to be rather stale, are there are plans to integrate it into the master branch?

**Comment by NickCraver** [comment]
We are currently working through OpenTSDB scaling issues here (which we've just made a major breakthrough on). The plan is to swap Orion into a branch and Bosun to become the master. The only holdup was OpenTSDB performance which we have ways to work around now.

**Comment by rajder** [comment]
What were the scaling issues you found?
We are only monitoring ~10 machines yet, with Bosun + Opserver running on two quite weak virtual machines which is working fine for now but I suspect we will need to scale up later.

**Comment by NickCraver** [comment]
The problems we're running into are queries with high tag cardinality in OpenTSDB. We're currently running denormalization on CPU and Memory metrics to make these a few orders of magnitude faster. It's different enough that I probably need to scrap the branch and re-do it though. Since it's a metric instead of tag denormalization a lot of the code assumptions fetching metrics are no longer valid.

**Comment by rajder** [comment]
Ok. I suppose fetching data for all hosts in the same query does not scale well with the number of hosts? I don't see any problems at ~10 monitored nodes, how many nodes are you monitoring? I am tempted to try solving the problem by simply fetching a single host for each query but since I don't see any performance issues it would probably be better to let you sort it out :)
If you choose to continue the current bosun branch I would like to call your attention to some bugfixes in https://github.com/opserver/Opserver/pull/98

**Comment by Janiels** [comment]
Sorry for the bump, but what is the progress on this?

**Comment by NickCraver** [comment]
We have just (hopefully) resolved our instability issues around HBase (which is what OpenTSDB runs on top of). There will be changes come in the next few weeks in both Bosun and Opserver that will allow me to have a full provider based on it. I'll be including both providers in the main branch (and have 2 different *types* of providers) which allows people to still use Orion if they want, rather than maintaining 2 separate branches where effectively one gets very little love.

**Comment by Janiels** [comment]
That is great! Thanks for the update.

**Comment by NickCraver** [comment]
This is alive and well in main but has significantly more integration in the overhaul branch. We're working on adding hardware, etc. Here's an idea of what that branch looks like if you're wanting to pull and test:

<img width="1130" alt="screen shot 2016-01-24 at 9 07 27 am" src="https://cloud.githubusercontent.com/assets/454813/12536675/feb3703c-c279-11e5-97ef-6ff24bdc5349.png">

<img width="991" alt="screen shot 2016-01-24 at 9 08 52 am" src="https://cloud.githubusercontent.com/assets/454813/12536685/24968898-c27a-11e5-930c-f55fe2d9450e.png">

It's a work in progress, but there will be a lot of fun with metrics soon where we can make graphs appear if the metric is present on the machine, etc. If you're on bosun and want to give it a whirl though, we're testing this branch on a production instance now and I'll try and wrap up the bits over the next few weeks enough for master...then keep adding.

Apologies for the delay here, the .Net Core stuff has taken a significant portion of my time, and I'll need to make SE.Exceptional (nearly there), MiniProfiler (a maybe, or switch to Glimpse) work at a minimum for the upcoming MVC6 move.

**Comment by NickCraver** [comment]
Oh just to add one here and maybe important to many, here's what a mobile phone view looks like on that branch. It's a Bootstrap layout in order to make adding new views, screen scaling, and eventually plugins all easier.

<img width="384" alt="screen shot 2016-01-24 at 9 14 09 am" src="https://cloud.githubusercontent.com/assets/454813/12536711/e1de1e48-c27a-11e5-94ca-8e78a3fb6021.png">

**Comment by NickCraver** [comment]
We're working on all the data, but more Bosun integration going in, here's first pass of a network panel:
<img width="1001" alt="screen shot 2016-01-31 at 10 50 41 pm" src="https://cloud.githubusercontent.com/assets/454813/12716095/2bafb004-c8ac-11e5-8a67-8c537aec2d85.png">

**Comment by NickCraver** [comment]
Bosun's up and running - closing this out to cleanup.
